compiler:
  solc:
    remappings:
      - "@openzeppelin/contracts-upgradeable=OpenZeppelin/openzeppelin-contracts-upgradeable@4.5.0"
      - "@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.5.0"
dependencies:
  - OpenZeppelin/openzeppelin-contracts@4.5.0
  - OpenZeppelin/openzeppelin-contracts-upgradeable@4.5.0
wallets:
  from_key: ${PRIVATE_KEY}
dotenv: .env
